FROM: alpine:3.7

RUN apk add --no-cache build-base python3
RUN pip install --upgrade pip
RUN pip install awscli

RUN pip install aws-sam-cli

WORKDIR /var/task

VOLUME /var/run/docker.sock

EXPOSE 3001

ENTRYPOINT ["/bin/sh"]